### ISSUE TITLE
[feat] adding support for push checks

### ISSUE THREAD

**Issue by venkatamutyala** [StatusCakeDev/terraform-provider-statuscake#141]
**Is your feature request related to a problem? Please describe.**
Creating push tests via terraform

**Describe the solution you'd like**
Being able to create push tests via terraform. It seems like other test types are supported

**Describe alternatives you've considered**
None at this time.

**Additional context**
We want to deploy services via terraform and ensure they are online using this push/heartbeat test. It's a multi-step manual and error prone process if we can't do this via terraform

**Comment by tomasbasham** [comment]
Duplicate of #74

**Comment by venkatamutyala** [comment]
Sorry, should have checked existing issues more closely.
