### ISSUE TITLE
Set 'follow_redirect' to true by default

### ISSUE THREAD

**Issue by tdmalone** [StatusCakeDev/terraform-provider-statuscake#17]
### Terraform Version
```sh
Terraform v0.11.7
+ provider.statuscake v0.2.0
```

### Affected Resource(s)
- [`statuscake_test`](https://www.terraform.io/docs/providers/statuscake/r/test.html)

v0.2.0 of this provider added support for the `follow_redirect` option, which by default Terraform sets to `false`:

![image](https://user-images.githubusercontent.com/900469/43309967-9a6b5dac-91c9-11e8-9141-aa62fdcc3b77.png)

The StatusCake UI however, when creating a new test, has this option on by default:

![image](https://user-images.githubusercontent.com/900469/43309988-ab179eae-91c9-11e8-9a6b-e90d70e997d1.png)

For consistency between Terraform and the UI, I'd suggest it would be good to use the same defaults where possible. For me, this manifested in diffs upon upgrading from v0.1.0 of the provider to v0.2.0, because my previous tests were implicitly created with 'follow redirects' turned on.

**Comment by matschaffer** [comment]
Hm, interesting. The API defaults to disabled: https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md

Wonder how many other places the UI and API disagree...

**Comment by matschaffer** [comment]
Thanks for the quick feedback on the 0.2.0 release.

I'll check the UI for myself but if you happen to see any other places the API and UI defaults disagree perhaps we can build a list and have terraform match the UI defaults.

**Comment by tdmalone** [comment]
Ohh... interesting! I didn't check that because I just assumed that the UI and API would match.

Despite the obvious inconsistency, I actually think Terraform should match the API. Terraform is more of a wrapper around the API than the UI, so I think this should be a StatusCake 'bug' rather than something Terraform should solve. I take this from seeing similar inconsistencies when comparing the AWS UI to the AWS Terraform provider... once you get your head around the inconsistencies, having the AWS Terraform provider work the same way as the AWS CLI, the AWS API, and AWS SDKs actually makes a lot more sense - and the real 'bug' is AWS' issue. I don't think StatusCake should be any different.

I've [tweeted StatusCake](https://twitter.com/tdmalone/status/1023022254404194304) for their thoughts on this.
