### ISSUE TITLE
Inconsistent http_check.content_matchers

### ISSUE THREAD

**Issue by OlegKunitsyn** [StatusCakeDev/terraform-provider-statuscake#194]
**Describe the bug**
Attribute content_matchers used in http_check in Terraform is not exposed via API.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a resource with content_matchers
2. Get it curl https://api.statuscake.com/v1/uptime/id   -H "Authorization: Bearer token"
3. Prepare main.tf like this
```
resource "statuscake_uptime_check" "check" {
  name           = "check"
  http_check {
    follow_redirects = true
    request_method   = "HTTP"
    timeout          = 15
  }
  monitored_resource {
    address = "https://example.com/"
  }
}
```
4. Run terraform plan
5. See "will be updated in-place" - content_matchers {}

**Expected behaviour**
http_check.content_matchers should be consistent via Terraform and API

**Comment by tomasbasham** [comment]
Hi @OlegKunitsyn. Content matchers are exposed by the API, as the Terraform provider uses these fields to set the matcher. The Terraform provider offers a slightly better abstraction over the raw API fields which are a little simpler to understand.

The fields in the API you're looking for are:
- `find_string`
- `include_header`
- `do_not_find`

I hope this helps
