### ISSUE TITLE
[Bugfix] remove the resource if it has been actually removed from the StatusCake

### ISSUE THREAD

**Issue by cazorla19** [StatusCakeDev/terraform-provider-statuscake#20]
The issue: when you remove the test manually from the UI, the provider instead of removing this in plan, just resetting all resource parameters. Eventually it must completely remove the resource, so you can add the fresh one instead.

**Comment by cob16** [comment]
can confirm the terraform trys to modify the resource instead of recreating it. This then fails when applied with `Error Updating StatusCake Test: HTTP error: 404 - 404 Not Found`
