### ISSUE TITLE
Contact Group not apply correctly

### ISSUE THREAD

**Issue by julienpierini** [StatusCakeDev/terraform-provider-statuscake#42]
When I try to create or update a `Test`, after the apply passed I can see the contact group on the `Test` overview:

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/32954578/61457588-ec708200-a968-11e9-96e1-83fd0f8904b9.png">

But when I go to the `Edit Test` section, there is no contact group at all:

![image](https://user-images.githubusercontent.com/32954578/61457830-71f43200-a969-11e9-8851-94361e862ce6.png)

So no mail or notifications are send, when a test fail.
The StatusCake API return me a `None` value on the variable `contact_group`.

Also when I import an existing `Test` with contact groups attached (create by hand) in the `tfstate` the `"contact_group"` is equal to `"null"`

I try with `Terraform v10, v11 and v12`.

**Comment by julienpierini** [comment]
You need to specify an array of `int` (with the ids of your contact_groups) in your tf file
(cf: `statuscake api` https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md) 
and not an array of `string` as indicated here:
https://www.terraform.io/docs/providers/statuscake/r/test.html

`terraform v12.4` e.g: 
```
resource "statuscake_test" "CACI_OAVPGS_API" {
  check_rate       = 300
  confirmations    = 5
  contact_group    = [133429, 133432]
  enable_ssl_alert = false
  follow_redirect  = true
  paused           = false
  status_codes     = "204,205,206,303,400,401,403,404,405,406,408,410,413,444,429,494,495,496,499,500,501,502,503,504,505,506,507,508,509,510,511,521,522,523,524,520,598,599"
  test_type        = "HTTP"
  timeout          = 40
  trigger_rate     = 4
  use_jar          = 0
  website_name     = "yourwebsite"
  website_url      = "https://yourwebsite"
}
```

**Comment by alaslums** [comment]
This caught me out too - I assumed contact_group array of strings meant the names of the contact groups.

Using the names would be better than IDs.

**Comment by marcinatvic** [comment]
I fell for the same. Would be nice to have docs updated to be more clear about this (if changing it to support names is non-trivial).
