### ISSUE TITLE
Feature request CRUD for Pagespeed Tests

### ISSUE THREAD

**Issue by balmas** [StatusCakeDev/terraform-provider-statuscake#50]
The StatusCake API includes support for CRUD of the Pagespeed tests. 

https://www.statuscake.com/api/Page%20Speed/Create%20Pagespeed%20Test.md

https://www.statuscake.com/api/Page%20Speed/Delete%20Pagespeed%20Test.md

https://www.statuscake.com/api/Page%20Speed/Update%20Pagespeed%20Test.md

https://www.statuscake.com/api/Page%20Speed/List%20Pagespeed%20Test.md

It would be nice to add this to the Statuscake provider.  Corresponding request opened in the statuscake client library that this provider uses: https://github.com/DreamItGetIT/statuscake/issues/49

**Comment by andrewn3wman7** [comment]
Hi @balmas , i forked the repo with pagespeed test support (i'm not a go expert) so be gentle :) if you want to try it : 

https://github.com/andrewn3wman7/terraform-provider-statuscake/blob/master/statuscake/resource_statuscakepagespeed.go

Any feedback is more than welcome

**Comment by balmas** [comment]
awesome thank you! I'll give it a try!
