### ISSUE TITLE
Unable to delete a test

### ISSUE THREAD

**Issue by yld** [StatusCakeDev/terraform-provider-statuscake#51]
### Terraform Version

terraform --version
Terraform v0.12.16
+ provider.aws v2.43.0
+ provider.external v1.2.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.statuscake v1.0.0

### Affected Resource(s)

- statuscake_test.google

### Terraform Configuration Files

After adding the following code (to test the provider)
```hcl
resource "statuscake_test" "google" {
  website_name = "google.com"
  website_url  = "www.google.com"
  test_type    = "HTTP"
  check_rate   = 300
  contact_id   = 12345
}
```

And after removing it from our hcl files, when applying:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # statuscake_test.google will be destroyed
  - resource "statuscake_test" "google" {
      - check_rate       = 0 -> null
      - confirmations    = 0 -> null
      - contact_id       = 12345 -> null
      - do_not_find      = false -> null
      - enable_ssl_alert = false -> null
      - follow_redirect  = false -> null
      - id               = "5348916" -> null
      - node_locations   = [] -> null
      - paused           = false -> null
      - port             = 0 -> null
      - test_id          = "5348916" -> null
      - timeout          = 0 -> null
      - trigger_rate     = 0 -> null
      - uptime           = 0 -> null
      - use_jar          = 0 -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

statuscake_test.google: Destroying... [id=5348916]

Error:


```

We've got an error without any explanations.
### Debug Output

(abstract with `TF_LOG="debug"`)
```
2020/01/03 15:41:33 [DEBUG] statuscake_test.google: apply errored, but we're indicating that via the Error pointer rather than returning it:
2020/01/03 15:41:33 [ERROR] <root>: eval: *terraform.EvalApplyPost, err:
2020/01/03 15:41:33 [ERROR] <root>: eval: *terraform.EvalSequence, err:
2020/01/03 15:41:33 [ERROR] <root>: eval: *terraform.EvalOpFilter, err:
2020/01/03 15:41:33 [TRACE] [walkApply] Exiting eval tree: statuscake_test.google (destroy)
2020/01/03 15:41:33 [TRACE] vertex "statuscake_test.google (destroy)": visit complete
```

### Panic Output
None

### Expected Behavior
statuscake_test.google should have been destroyed **and** removed from the state.
That was the case after several apply, but the resource remained in terraform state.

Manually removing is a workaround:
`terragrunt state rm statuscake_test.google
`
### Actual Behavior
Error without any explanation

### Steps to Reproduce
See above.

**Comment by Baryczka** [comment]
This issue happen to me as well when I removed some alerts by hand from the UI and none command helped to refresh state as it was always reporting all alerts existing. As you stated, workaround was to remove manually given tests and recreate good state again.
