### ISSUE TITLE
Feature request: locations data source

### ISSUE THREAD

**Issue by lloydhazlett** [StatusCakeDev/terraform-provider-statuscake#52]
It would be very helpful if this provider included a data source for [test server locations](https://www.statuscake.com/kb/knowledge-base/what-are-your-ips/), similar to the [cloudflare_ip_ranges](https://www.terraform.io/docs/providers/cloudflare/d/ip_ranges.html) CloudFlare provider [data source](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/data_source_ip_ranges.go). Use cases:

- Selecting ``node_locations`` for ``statuscake_test`` resources by country
- Adding location IP addresses to firewall rule resources

**Comment by andrewn3wman7** [comment]
vaibhavkhurana built a nice terraform module : https://github.com/vaibhavkhurana2018/terraform-http-statuscake-whitelist
@lloydhazlett is it what you're looking for ?
