### ISSUE TITLE
error updating statuscake user agent

### ISSUE THREAD

**Issue by tjend** [StatusCakeDev/terraform-provider-statuscake#53]
### Terraform Version
Terraform v0.11.14 and v0.12.21
+ provider.statuscake v1.0.0

### Affected Resource(s)
- statuscake_test

### Terraform Configuration Files
```hcl
resource "statuscake_test" "test" {
...
  user_agent = "test123"
}
```

### Debug Output
https://gist.github.com/tjend/b200a20038091df631c1e7c76070cc99

### Expected Behavior
User agent should be updated within statuscake.

### Actual Behavior
An error occurs("No data has been updated (is any data different?)"), statuscake is not updated, but the tfstate file is updated as if it worked.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
When not using a custom user agent, no error occurs. The api documentation for statuscake, https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md, currently doesn't mention the user agent. However testing with curl works as expected, "curl -H "API: [key]" -H "Username: [user]" -d "TestID=5421105&UserAgent=test123" -X PUT https://app.statuscake.com/API/Tests/Update".

**Comment by andrewn3wman7** [comment]
Same behavior on my side, it's because the field UserAgent is not available when you get the test (https://www.statuscake.com/api/Tests/Get%20Detailed%20Test%20Data.md), i'm checking with statuscake support to add it.
