### ISSUE TITLE
Terraform Registry missing ARM64 version of StatusCake Provider

### ISSUE THREAD

**Issue by SuperMatt** [StatusCakeDev/terraform-provider-statuscake#57]
### Terraform Version
v0.13.5

### Affected Resource(s)
StatusCake provider

### Terraform Configuration Files
n/a

### Expected Behavior
What should have happened?

### Actual Behavior
```
Error: Failed to install provider

Error while installing -/statuscake v1.0.0: provider
registry.terraform.io/-/statuscake 1.0.0 is not available for linux_arm64
```

### Steps to Reproduce
Run a terraform init on a project with a statuscake provider, but on an ARM64 machine, such as a raspberry pi 4

**Comment by kalin** [comment]
Just want to highlight how important this is now that we're a year into Apple Silicon. We will probably move our tests to a different provider soon because of this as we move more of our infrastructure to terraform.
