### ISSUE TITLE
Feature request: SSL Tests

### ISSUE THREAD

**Issue by pietermees** [StatusCakeDev/terraform-provider-statuscake#6]
It would be great if we could also configure SSL tests with this provider

**Comment by devhops** [comment]
+1 for this, I would also make use of this feature.

**Comment by cjs226** [comment]
Any chance the PR by @ivanschwarz will be reviewed and (hopefully) merged soon?

**Comment by tdmalone** [comment]
@cjs226 The [PR you're referring to ](https://github.com/terraform-providers/terraform-provider-statuscake/pull/26) is actually for #16, which covers the SSL validation option on uptime tests (perhaps that's what you're after? it's a different thing to support for SSL tests, which is a different StatusCake test type)

**Comment by cjs226** [comment]
@tdmalone yes, I am looking forward to SSL validation on uptime tests.  Any idea when there will be a new release that includes it?

**Comment by matschaffer** [comment]
This is fixed by https://github.com/terraform-providers/terraform-provider-statuscake/pull/35

Will provide info regarding the release on https://github.com/terraform-providers/terraform-provider-statuscake/issues/38

**Comment by tdmalone** [comment]
@matschaffer This isn't fixed by #35 - that PR is for the SSL validation on uptime tests and fixes #16.
This issue covers support for SSL Tests, which is a different feature (new resource).

**Comment by matschaffer** [comment]
Whoops. Made the same mistake @cjs226 did. 😊

**Comment by WillPlatnick** [comment]
Is anybody working on this? If not, I may take a stab at it.

**Comment by matschaffer** [comment]
Looks like https://github.com/terraform-providers/terraform-provider-statuscake/pull/41/files has it. Helping test would be great!
