### ISSUE TITLE
Archived or not?

### ISSUE THREAD

**Issue by jakubbujny** [StatusCakeDev/terraform-provider-statuscake#60]
https://github.com/StatusCakeDev/terraform-provider-statuscake/commit/daf520c7ff891fd8583436fbf02a36e1c49463ba 

vs 

https://github.com/StatusCakeDev/terraform-provider-statuscake/commit/b7966c40c2b37d543595a636ceb0ae5429c9faa1

so is it archived or not?

What's the relation to https://github.com/thde/terraform-provider-statuscake which seems to have far more features now?

**Comment by tomasbasham** [comment]
There is no relation to other providers. StatusCake took ownership of this provider last year from HashiCorp (original developers) and have recently released a new version of the provider.
