### ISSUE TITLE
Feature request: Contact groups and Integrations

### ISSUE THREAD

**Issue by vatima2016** [StatusCakeDev/terraform-provider-statuscake#63]
Hi there,

the provider should support Contact groups and Integrations to avoid UI usage by using for example integration IDs as outputs from the [TF PagerDuty provider](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs). I know that the StatusCake API V1 does not support Integrations yet, but I did not find out myself how I could report a feature request for the StatusCake API. Does anybody know that?

StatusCake seems to be loosing competition battle in this area: UptimeRobot API supports the full cycle of creating uptime tests connected to the alert contacts. PagerDuty support was added recently to their API, so I suppose that their TF provider will add it soon too.

P.S. I know that there is good [alternative TF provider implementation](https://registry.terraform.io/providers/ackama/statuscake/latest) for StatusCake , which is blocked on the lack of API endpoint for the Integrations too.

**Comment by tomasbasham** [comment]
Hello. Thank you for your suggestion. As we have more recently been transferred ownership of the Terraform provider by HashiCorp, it is currently undergoing a rewrite to better reflect the structure of our new API. Whilst the initial release will not include the creation of integration this is something on our API roadmap.

Contact groups however will appear in the new release of the provider as they do in the API.

**Comment by tomasbasham** [comment]
An API endpoint for integrations has been added to the StatusCake developers backlog
