### ISSUE TITLE
Variable statuscake_custom_endpoint not optional in provider configuration

### ISSUE THREAD

**Issue by Eagle-One1** [StatusCakeDev/terraform-provider-statuscake#65]
**Describe the bug**
The var statuscake_custom_endpoint seems to not be optional in provider configuration whereas the documentation say it is

**To Reproduce**
Use the provider as in the doc examples, with only api_token in the provider configuration

**Expected behavior**
No need to set statuscake_custom_endpoint, the default var should be "https://api.statuscake.com/" I think,

**Additional context**
Thanks for your job with the 2.x which seems to be have more functionalities and flexibility

**Comment by tomasbasham** [comment]
Thank you for reporting this. This is currently under investigation.

**Comment by tomasbasham** [comment]
This has been fixed in version 2.0.1-pre. It is still in beta and will hopefully be in GA shortly
