### ISSUE TITLE
Use Integrations in Contract Groups by Name not ID

### ISSUE THREAD

**Issue by martinseener** [StatusCakeDev/terraform-provider-statuscake#73]
**Is your feature request related to a problem? Please describe.**
I wanted to use existing Slack and PagerDuty Integrations in new Contact Groups created using the terraform provider. The docs say, I have to add them by their ID but I cannot get their ID (or I don't know how to get their ID). I at least can't find out the Integration ID from the UI or API.

**Describe the solution you'd like**
Instead it would be nice to use the Integration name or any other (API-) retrievable information that's unique.

**Comment by tomasbasham** [comment]
Thanks for making the issue. Unfortunately this is more of a limitation with our current API than the provider. It is without our backlog to expand upon the API to include this feature.

**Comment by martinseener** [comment]
Do you have an idea when this feature is there? Or can you otherwise tell me how I can get the ID otherwise (through web for example)?
I mean if it's possible to set the ID and use it, I should be able to obtain it "somehow"

**Comment by tomasbasham** [comment]
You should be able to get the ID of the integration from the integrations page of the StatusCake web UI.

**Comment by martinseener** [comment]
Thanks a lot! I now see the IDs for the Integrations. Hope the API Team can also make this available in the API (and your Team here in the integration soon). Would be super helpful.
Thank you for your effort!

**Comment by tomasbasham** [comment]
Thank you. It's on our roadmap to improve the API, including adding missing features such as this
