### ISSUE TITLE
Support for Push Tests

### ISSUE THREAD

**Issue by briananstett** [StatusCakeDev/terraform-provider-statuscake#74]
**Is your feature request related to a problem? Please describe.**
It would be helpful if there was a Terraform resources for [Push Tests](https://www.statuscake.com/kb/knowledge-base/what-is-push-monitoring/).

**Describe the solution you'd like**
A new push monitor/test resource. 

**Describe alternatives you've considered**
Or perhaps expending the currently uptime check resources to support push tests?

**Additional context**
NA

**Comment by briananstett** [comment]
Hmmm

**Comment by macropin** [comment]
Can we please get this reopened?

**Comment by nodesocket** [comment]
Would also appreciate push test support.

**Comment by Teasel-Ian** [comment]
Still hoping to get full terraform support for statuscake!

**Comment by dougbradbury** [comment]
we'd love to see this feature as well!

**Comment by dougbradbury** [comment]
Does the API even support the creation of push tests?  I'm not seeing it in the documentation.

**Comment by tomasbasham** [comment]
The current API does not support push tests. We hope to include this in the near future.

**Comment by dougbradbury** [comment]
Thanks, @tomasbasham - what is the best place to keep an eye on the feature so that we can know when it's available?

**Comment by saliceti** [comment]
The API now supports heartbeat (push) tests: https://developers.statuscake.com/api/#tag/heartbeat
It would be great to have it in terraform

**Comment by nodesocket** [comment]
@saliceti awesome. Can we get this added to the Terraform module?

**Comment by tomasbasham** [comment]
We're looking to add this fairly soon. The corresponding change in the Go SDK has been linked above.

**Comment by dougbradbury** [comment]
@tomasbasham - I am confused as to why the issue was reopened?  Is this change released and does it work?

**Comment by tomasbasham** [comment]
Hi @dougbradbury this was reopened because the change was found to have issues before it was about to be released. So this issue is still under development

**Comment by tomasbasham** [comment]
A version of the provider containing a heartbeat monitoring resource (v2.2.0) is now available. Documentation for the resource can be found [here](https://registry.terraform.io/providers/StatusCakeDev/statuscake/latest/docs/resources/heartbeat_check)
