### ISSUE TITLE
Import Documentation / Example?

### ISSUE THREAD

**Issue by Firefishy** [StatusCakeDev/terraform-provider-statuscake#77]
Could an example be included for how to import existing statuscake configuration?

An example using `terraform import` or other suitable method.

**Comment by tomasbasham** [comment]
Hi @Firefishy, thanks for point this out to us. We'll add these shortly. In the meantime resource can be imported using the following command format:

```bash
terraform import <resource>.<name> <ID>
```

For example:

```bash
terraform import statuscake_contact_group.default 123456
terraform import statuscake_uptime_check.google 123456
```

**Comment by tomasbasham** [comment]
bump, keeping open

**Comment by tomasbasham** [comment]
#81
