### ISSUE TITLE
Feature request: data source statuscake_contact_group

### ISSUE THREAD

**Issue by tguvdamm** [StatusCakeDev/terraform-provider-statuscake#78]
**Is your feature request related to a problem? Please describe.**
Contact groups are used across repositories. It would be useful if we can use a data source to get the contact group so that we can validate we have the right contact group.

**Describe the solution you'd like**
A data resource for statuscake_contact_group, which mirrors the [statuscake_contact_group resource](https://registry.terraform.io/providers/StatusCakeDev/statuscake/latest/docs/resources/contact_group).

**Describe alternatives you've considered**
* Hard coding the contact group ids, but these are magic numbers, which are undesirable.

**Comment by tomasbasham** [comment]
Sounds like a great feature. We'll try get this implemented
