### ISSUE TITLE
`monitored_resource.address` causes a destroy/create

### ISSUE THREAD

**Issue by jw-maynard** [StatusCakeDev/terraform-provider-statuscake#84]
**Is your feature request related to a problem? Please describe.**
I'm mostly wondering why changing the `address` causes Terraform to want to destroy and recreate a monitor in StatusCake. In my case I'm using `http_checks` on the `statuscake_uptime_check` resource. If I got into the StatusCake UI I can change the URL of the check without a problem so it seems like the Terraform provider should be able to accomplish the same without recreating the whole check and, presumably, loosing the history associated with the check.

**Describe the solution you'd like**
It would be best if the URL could be updated in place.

**Describe alternatives you've considered**
I'm not sure what other solutions inside Terraform there would be. Right now as a workaround I manually update the URL in the UI and then rerun the plan in Terraform but this kinda defeats the purpose of Terraform managing these resources.

**Additional context**

**Comment by tomasbasham** [comment]
The main reason for this behaviour was to prevent invalidating check history when the address is pointed to a completely different endpoint. However we do understand that sometimes an address will change for the same endpoint and that this behaviour does not suit this use case. This decision runs through both the provider and the API through which it communicates [link](https://www.statuscake.com/api/v1/#tag/uptime/operation/update-uptime-test). However this may be a decision we're forced to reverse.

For now, continue to make these kinds of changes through the UI and aligning the TF state with a plan/apply. We'll look further into this behaviour.

**Comment by jw-maynard** [comment]
Thanks for the reply @tomasbasham
