### ISSUE TITLE
Is this provider compatible with the API V1 or V2?

### ISSUE THREAD

**Issue by rodrigopinto** [StatusCakeDev/terraform-provider-statuscake#85]
I wanted to confirm if the current version of this terrafor provider is compatible with the API V2.

I mean, it uses https://github.com/StatusCakeDev/statuscake-go under the hood, I didn't find any reference or branch mentioning its compatibility or plans for migrating to the API V2. Could you confirm it?

**Comment by tomasbasham** [comment]
Hi @rodrigopinto. Yes, the latest version of the provider makes use of statuscake-go. Unlike the previous version of the provider (pre v2) all the code has been written and is to be maintained by StatusCake, including the Go library that underpins it.

**Comment by rodrigopinto** [comment]
@tomasbasham, thanks for confirming!
