### ISSUE TITLE
Bug sending custom headers for requests

### ISSUE THREAD

**Issue by marceloboeira** [StatusCakeDev/terraform-provider-statuscake#88]
**Describe the bug**

When migrating from terraform v1 provider, we discovered that the v2 provider introduced a bug that makes it impossible to send headers because they are not formatted correctly.

```json
"custom_header": "{\"Content-Type\":\"text/html; charset=utf-8\"}",
```
vs
```json
"custom_header": "{ Content-Type = \"text/html; charset=utf-8\" }",
```

**To Reproduce**

The code used to request a string:

```terraform
resource "statuscake_test" "my_test" {
  custom_header   = `{ Content-Type = \"text/html; charset=utf-8\"}`
}
```

And then it switched to request a `map(string)`
```terraform
resource "statuscake_uptime_check" "my_test" {
  ...
  http_check {
    request_headers  = {
      "Content-Type": "text/html; charset=utf-8"
    }
  } 
  ...
}
```

**Additional context**

For me, it seems related to the fact that the `map(string)` is sent directly to the API without serializing it to JSON:

https://github.com/StatusCakeDev/terraform-provider-statuscake/blob/master/internal/provider/resource_uptime_check.go#L167-L173

https://github.com/StatusCakeDev/terraform-provider-statuscake/blob/master/internal/provider/resource_uptime_check.go#L914-L919

**Comment by tomasbasham** [comment]
Can you verify that it works when configuration looks like this:

```hcl
resource "statuscake_uptime_check" "my_test" {
  ...
  http_check {
    request_headers  = {
      Content-Type = "text/html; charset=utf-8"
    }
  } 
  ...
}
```

This is how it is written in the documentation

**Comment by marceloboeira** [comment]
Sorry, that was a typo, my code is exactly as you shared, with `=`.

**Comment by tomasbasham** [comment]
I've tried this and I am able not able to reproduce the problem. Using the code above I was able to save the headers to the test.

```hcl
resource "statuscake_uptime_check" "google" {
  name           = "DEMO"
  check_interval = 1800
  confirmation   = 2
  trigger_rate   = 30

  http_check {
    request_headers = {
      Content-Type = "text/html; charset = utf-8"
    }
    status_codes = ["200"]
  }

  monitored_resource {
    address = "google.com"
  }

  regions = [
    "amsterdam",
    "frankfurt",
    "london",
  ]
}
```

![image](https://user-images.githubusercontent.com/3389856/189170704-f0dfaabd-3f8d-4875-a2b5-a89bd5182d55.png)

**Comment by marceloboeira** [comment]
I'll have to try figuring what's causing it then, I still see:
<img width="545" alt="Screenshot 2022-09-09 at 11 19 02" src="https://user-images.githubusercontent.com/1898225/189316881-3aee60fe-abb3-4277-b283-ca9b2854255f.png">

**Comment by marceloboeira** [comment]
also, unrelated but the formating tooltip is missing a `}` at the end.

**Comment by tomasbasham** [comment]
> also, unrelated but the formating tooltip is missing a } at the end.

Ah yes, you're right. I'll let our frontend team aware of this.

**Comment by tomasbasham** [comment]
@marceloboeira Is this issue still causing you problems?
