### ISSUE TITLE
status_codes in http_check block should be optional and have sane defaults

### ISSUE THREAD

**Issue by alter3d** [StatusCakeDev/terraform-provider-statuscake#89]
In the 1.x version of the provider, the `status_codes` parameter to the `statuscake_test` resources was optional and had sane defaults.  

In the 2.x version of the provider, the equivalent parameter is required, which means that we need to supply a (long) list of HTTP response codes we want to trigger a failure for every single check we set up.

In our experience with the 1.x provider, the defaults were fine in the vast majority of cases, meaning the behaviour of the 2.x provider is needlessly verbose.

**Comment by d0x2f** [comment]
I feel like it'd be more appropriate to specify which status codes are expected rather than unexpected.
It's easier to list status codes (most likely 1) you expect your request to generate than it is to list every other possible status code.
Much less verbose as well.

**Comment by lloydhazlett** [comment]
> I feel like it'd be more appropriate to specify which status codes are expected rather than unexpected.

Agree, this is a longstanding issue with the console as well. Would love to see it finally addressed there too, though at least returning this resource to the optional behaviour of 1.x would mean we can continue to largely ignore it in console.

**Comment by tomasbasham** [comment]
Thank you for the feedback. We look to get this issue resolved in the next release. We'll set sensible defaults for this field when not specified such that the behaviour is like that of the 1.x branch of the provider.
