### ISSUE TITLE
Invalid params causes the provider to crash

### ISSUE THREAD

**Issue by marceloboeira** [StatusCakeDev/terraform-provider-statuscake#90]
**Describe the bug**
Invalid regions crash the provider without an informative message
 
**To Reproduce**

1. Create an uptime test with an invalid region
```hcl
resource "statuscake_uptime_check" "debug" {
  name           = "[DEBUG] THIS IS A TEST"
  check_interval = 30
  regions        = [
    "invalid",
  ]

  monitored_resource {
    address = "https://google.com"
  }

  http_check {
    request_method   = "HTTP"
    status_codes     = [
      "500"
    ]
  }
}
```
3. Try plan/apply
4. See it fail without a good error

```shell
╷
│ Error: failed to create uptime test: The provided parameters are invalid. Check the errors output for detailed information.
│
│   with statuscake_uptime_check.debug,
│   on foo.tf line 18, in resource "statuscake_uptime_check" "debug":
│   18: resource "statuscake_uptime_check" "debug" {
│
```

https://gist.github.com/marceloboeira/89c5ed85fbed1f5ea76edee3434d08fa#file-main-tf

Here is the full error log and failing test case:

https://gist.github.com/marceloboeira/89c5ed85fbed1f5ea76edee3434d08fa

**Expected behavior**

Error on plan (or even apply) with the information that the error is caused by the wrong region code (or any possible message the API is returning for failure).

**Additional context**

By removing the region's block OR using valid regions, the code works; it just took me a long time to debug and find out that the problem was the region...

**Comment by tomasbasham** [comment]
Thank for reporting this. We're currently working on providing better error messaging when something goes wrong. It seems it was just being swallowed

**Comment by marceloboeira** [comment]
Awesome!
