### ISSUE TITLE
Random TF plan failures ("failed to get uptime test with ID")

### ISSUE THREAD

**Issue by r2ronoha** [StatusCakeDev/terraform-provider-statuscake#91]
**Describe the bug**
The terraform plan randomly fails with the following error
```
│ Error: failed to get uptime test with ID:
│
│   with statuscake_uptime_check.proxy["e7bc74d659a3166f"],
│   on monitoring.tf line 26, in resource "statuscake_uptime_check" "proxy":
│   26: resource "statuscake_uptime_check" "proxy" {
```

A DEBUG plan only adds the following
```
2022-09-26T10:22:25.327Z [ERROR] vertex "statuscake_uptime_check.proxy" error: failed to get uptime test with ID:
```

**To Reproduce**
Run TF plan multiple times until the error happens.

**Expected behavior**
Plan consistently succeeds.

**Additional context**
Using latest version 2.0.4

**Comment by tomasbasham** [comment]
I have only been able to replicate this issue by increasing the number of requests the provider is allowed to make within a second. That is the `rps` setting in the provider block. The default value for this is 4 which is below the current ratelimit. Do you have a lot of StatusCake resources within you configuration?

**Comment by r2ronoha** [comment]
Thanks for the feedback. I've contacted StatusCake, and we are indeed hitting the 5 rps limit as we may run multiple plans for different locations simultaneously.
I think we can close this bug
