### ISSUE TITLE
Provide a way to set the api token of the provider as an env var

### ISSUE THREAD

**Issue by lra** [StatusCakeDev/terraform-provider-statuscake#92]
**Is your feature request related to a problem? Please describe.**

Setting up the provider requires to set the api_token in the provider block:
```
provider "statuscake" {
  api_token = "my-api-token"
}
```

**Describe the solution you'd like**

I'd like the provider to look at some env var by itself, and only fallback to `api_token` if this env var is not set.

**Describe alternatives you've considered**

To not harcode the api token, I have to explicitely define a `TF_VAR_` terraform variable that I use in the provider

**Comment by tomasbasham** [comment]
The API token can be specified with the environment variable `STATUSCAKE_API_TOKEN`

**Comment by lra** [comment]
Works, thanks. It should be documented.
