### ISSUE TITLE
Set provider api key via envar

### ISSUE THREAD

**Issue by nodesocket** [StatusCakeDev/terraform-provider-statuscake#94]
Since I don't want to hardcode api tokens and keys into my codebase, is it possible to use an envar to define the provider api key? Typically this is done via envar.

**Comment by tomasbasham** [comment]
#92 It can be specified with `STATUSCAKE_API_TOKEN`

**Comment by nodesocket** [comment]
Ok thanks. Would be awesome to add that note to the documentation on this page:

https://registry.terraform.io/providers/StatusCakeDev/statuscake/latest/docs#example-usage
